import asyncio
from playwright.async_api import async_playwright
import os
import dotenv

# Загружаем учетные данные (создайте файл .env с EMAIL и PASSWORD)
dotenv.load_dotenv()
EMAIL = os.getenv('EMAIL')
PASSWORD = os.getenv('PASSWORD')
COOKIE_FILE = 'cookies.txt'

async def update_youtube_cookies():
    """Автоматически логинится в YouTube и сохраняет cookies в Netscape формате"""
    
    async with async_playwright() as p:
        # Запускаем браузер (headless=false для первого запуска, потом можно headless=true)
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()
        
        print("🔐 Логинимся в Google...")
        
        # Переходим на страницу логина Google
        await page.goto('https://accounts.google.com/')
        
        # Вводим email
        await page.fill('input[type="email"]', EMAIL)
        await page.click('#identifierNext')
        await page.wait_for_timeout(2000)
        
        # Вводим пароль
        await page.fill('input[type="password"]', PASSWORD)
        await page.click('#passwordNext')
        
        # Ждем завершения логина
        await page.wait_for_timeout(5000)
        
        # Переходим на YouTube
        await page.goto('https://www.youtube.com/robots.txt')
        await page.wait_for_timeout(2000)
        
        # Получаем cookies
        cookies = await context.cookies()
        
        # Конвертируем в Netscape формат
        netscape_cookies = convert_to_netscape(cookies)
        
        # Сохраняем в файл
        with open(COOKIE_FILE, 'w') as f:
            f.write(netscape_cookies)
        
        print(f"✅ Cookies сохранены в {COOKIE_FILE}")
        
        await browser.close()

def convert_to_netscape(cookies):
    """Конвертирует cookies из JSON в Netscape формат для yt-dlp"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# This file was generated by cookie_updater.py"
    ]
    
    for cookie in cookies:
        domain = cookie.get('domain', '')
        domain_specified = 'TRUE' if domain.startswith('.') else 'FALSE'
        path = cookie.get('path', '/')
        secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
        expires = str(int(cookie.get('expires', 0))) if cookie.get('expires') else '0'
        name = cookie.get('name', '')
        value = cookie.get('value', '')
        
        line = f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
        lines.append(line)
    
    return '\n'.join(lines)

if __name__ == '__main__':
    asyncio.run(update_youtube_cookies())
